version: '3'

services:
  backend:
    build: ./
    container_name: chatapp
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - database
    networks:
      - nestjs_network

  database:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=mydb
    volumes:
      - ./cache/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - nestjs_network

networks:
  nestjs_network:
    driver: bridge
